name: Build Windows Binary
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Build UI
        run: |
          cd client
          pnpm install
          pnpm run build
          cd ..

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Windows
        run: cargo build --release

      - name: Zip executable
        run: Compress-Archive -Path target\release\onetagger.exe -DestinationPath onetagger-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: onetagger-windows
          path: onetagger-windows.zip

